# Generated by Django 4.2.4 on 2023-12-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maketrip',
            name='drop_date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='maketrip',
            name='dropoff',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='maketrip',
            name='pick_date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='maketrip',
            name='pickup',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='maketrip',
            name='time',
            field=models.CharField(max_length=30),
        ),
    ]
